#!/bin/sh

set -eu

CONFIG="${CKAN_CONFIG}/ckan.ini"

if [ -e "$CONFIG" ]; then
  echo "Already configured... SKIP"
  exit 0
fi

abort () {
  echo "$@" >&2
  exit 1
}

write_config () {
  "$CKAN_HOME"/bin/paster make-config ckan "$CONFIG"

  "$CKAN_HOME"/bin/paster --plugin=ckan config-tool "$CONFIG" -s DEFAULT -e \
      "debug = True"

  "$CKAN_HOME"/bin/paster --plugin=ckan config-tool "$CONFIG" -e \
      "sqlalchemy.url = $(link_postgres_url)" \
      "solr_url = $(link_solr_url)" \
      "ckan.storage_path = /var/lib/ckan" \
      "email_to = wen.li@ucl.ac.uk" \
      "ckan.plugins = datastore datapusher pdf_view recline_view text_view cdrcmeta" \
      "ckan.site_url = http://localhost" \
      "ckan.datapusher.url = http://localhost:8800" \
      "ckan.datastore.write_url = $(link_postgres_url $CKAN_DATASTORE_WRITER $CKAN_DATASTORE_WRITEPASS $CKAN_DATASTORE_DB)" \
      "ckan.datastore.read_url = $(link_postgres_url $CKAN_DATASTORE_READER $CKAN_DATASTORE_READPASS $CKAN_DATASTORE_DB)" \
      "error_email_from = ${CKAN_ERROR_EMAIL_FROM:-ckan@example.org}"

  if [ -n "$CKAN_ERROR_EMAIL" ]; then
    sed -i -e "s&^#email_to.*&email_to = ${CKAN_ERROR_EMAIL}&" "$CONFIG"
  fi
}

# link_postgres_url(user, pass, db)
link_postgres_url () {
  local user=${1:-$DB_ENV_POSTGRESQL_USER}
  local pass=${2:-$DB_ENV_POSTGRESQL_PASS}
  local host=$DB_PORT_5432_TCP_ADDR
  local port=$DB_PORT_5432_TCP_PORT
  local db=${3:-$DB_ENV_POSTGRESQL_DB}
  echo "postgresql://${user}:${pass}@${host}:${port}/${db}"
}

link_solr_url () {
  local host=$SOLR_PORT_8983_TCP_ADDR
  local port=$SOLR_PORT_8983_TCP_PORT
  echo "http://${host}:${port}/solr/ckan"
}

write_config
