#!/bin/bash
set -eu

if [ ${CKAN_TEST_MODE:-0} -ne 1 ]; then
  exit 0;
fi


CONFIG="$CKAN_HOME"/src/ckan/test-core.ini

# Install dev dependencies
"$CKAN_HOME"/bin/pip install -r "$CKAN_HOME"/src/ckan/dev-requirements.txt

# Modify the default test-core.ini to link to db and solr
# link_postgres_url(user, pass, db)
link_postgres_url () {
  local user=${1:-$DB_ENV_POSTGRESQL_USER}
  local pass=${2:-$DB_ENV_POSTGRESQL_PASS}
  local host=$DB_PORT_5432_TCP_ADDR
  local port=$DB_PORT_5432_TCP_PORT
  local db=${3:-$DB_ENV_POSTGRESQL_DB}
  echo "postgresql://${user}:${pass}@${host}:${port}/${db}"
}

link_solr_url () {
  local host=$SOLR_PORT_8983_TCP_ADDR
  local port=$SOLR_PORT_8983_TCP_PORT
  echo "http://${host}:${port}/solr/ckan"
}

"$CKAN_HOME"/bin/paster --plugin=ckan config-tool "$CONFIG" -e \
    "sqlalchemy.url = $(link_postgres_url)" \
    "solr_url = $(link_solr_url)" \
    "ckan.site_url = http://localhost" \
    "ckan.datapusher.url = http://localhost:8800" \
    "ckan.datastore.write_url = $(link_postgres_url $CKAN_DATASTORE_WRITER $CKAN_DATASTORE_WRITEPASS $CKAN_DATASTORE_DB)" \
    "ckan.datastore.read_url = $(link_postgres_url $CKAN_DATASTORE_READER $CKAN_DATASTORE_READPASS $CKAN_DATASTORE_DB)" \

# Running the tests
"$CKAN_HOME"/bin/nosetests --ckan --reset-db --with-pylons=$CONFIG "$CKAN_HOME"/src/ckan/ckan/new_tests
