// Generated by LiveScript 1.3.1
(function(){
  var casper, uuid;
  casper = require('casper').create();
  uuid = require('node-uuid');
  casper.start("http://localhost/user/login", function(){
    return this.fill("form[action='/login_generic?came_from=/user/logged_in']", {
      login: 'ckan',
      password: 'ckan'
    }, true);
  });
  casper.thenOpen("http://localhost/dataset/new", function(){
    this.echo(this.getCurrentUrl());
    this.sendKeys('form#dataset-edit input#field-title', "Census UK 2011 (" + uuid.v4() + ")");
    return this.echo(this.evaluate(function(){
      return $('.slug-preview-value').text();
    }));
  });
  casper.then(function(){
    return this.click('form#dataset-edit button[type="submit"]');
  });
  casper.then(function(){
    this.echo(this.getCurrentUrl());
    this.fill('form#resource-edit', {
      upload: "./test_data/Workplace population.csv",
      name: "Workplace Population (" + uuid.v4() + ")",
      format: "CSV"
    });
    return this.click('button[value="go-metadata"]');
  });
  casper.then(function(){
    return this.echo(this.evaluate(function(){
      return $('a.heading').href();
    }));
  });
  casper.run();
}).call(this);
